- name: Create Ansible inventory
  run: |
    IP=$(cat ansible/host_ip.txt)
    echo "[monitoring]" > ./ansible/hosts
    echo "${IP} ansible_user=ubuntu ansible_ssh_private_key_file=/home/runner/.ssh/id_rsa" >> ./ansible/hosts
