- name: Déployer la stack monitoring avec images custom
  hosts: all
  become: true
  vars:
    prometheus_image: prom/prometheus:latest
    grafana_image: custom-grafana:latest

  tasks:
    - name: Installer Docker
      apt:
        name: docker.io
        state: present
        update_cache: true

    - name: Activer et démarrer Docker
      systemd:
        name: docker
        enabled: true
        state: started

    - name: Lancer Prometheus
      docker_container:
        name: prometheus
        image: "{{ prometheus_image }}"
        state: started
        restart_policy: always
        ports:
          - "9090:9090"
        volumes:
          - /etc/prometheus:/etc/prometheus

    - name: Lancer Grafana custom
      docker_container:
        name: grafana
        image: "{{ grafana_image }}"
        state: started
        restart_policy: always
        ports:
          - "3000:3000"
