# name: Deploy Monitoring Stack

# on:
#   push:
#     branches: [main]

# env:
#   PUSH_TO_DOCKER: false # <--- mets true si tu veux activer le push

# jobs:
#   build-and-deploy:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout
#         uses: actions/checkout@v3

#       - name: Build Grafana Image
#         run: docker build -t custom-grafana ./grafana

#       - name: Push to Docker Hub (optional)
#         if: env.PUSH_TO_DOCKER == 'true'
#         env:
#           DOCKER_USER: ${{ secrets.DOCKER_USER }}
#           DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
#         run: |
#           echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
#           docker tag custom-grafana $DOCKER_USER/custom-grafana:latest
#           docker push $DOCKER_USER/custom-grafana:latest

#       - name: Deploy with Ansible
#         run: ansible-playbook -i ansible/inventory/hosts.yml ansible/playbooks/playbook.yml

name: Deploy Infrastructure & Configure Server

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: Terraform Apply
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        working-directory: ./terraform
        run: terraform init

      - name: Terraform Apply
        working-directory: ./terraform
        run: terraform apply -auto-approve

  ansible:
    name: Run Ansible
    runs-on: ubuntu-latest
    needs: terraform

    env:
      ANSIBLE_HOST_KEY_CHECKING: "False"

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Get EC2 IP from Terraform output
        working-directory: ./terraform
        run: terraform output -raw instance_ip > ../ansible/host_ip.txt

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_rsa
          echo -e "Host *\n\tStrictHostKeyChecking no\n" > ~/.ssh/config

      - name: Create Ansible inventory
        run: |
          IP=$(cat ansible/host_ip.txt)
          echo "[monitoring]" > ansible/hosts
          echo "$IP ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/id_rsa" >> ansible/hosts

      - name: Install Ansible
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible

      - name: Run Ansible Playbook
        working-directory: ./ansible
        run: ansible-playbook -i hosts playbook.yml
